spring:
  profiles:
    active: local

custom:
  property:
    single: custom-property
    comlist: comma,separated,list,to,value
    ymllist:
      - yaml
      - list
      - to
      - spring
      - value
# test

# jonguk test branch github